
robot_motion_config: factory/tasks/config/robot_motion_fr3_sim.yaml

dataset:
  repo_id: pick_and_place_black_package_delta      # info.json 里的 repo_id
  root: /home/hanyu/code/HIROLRobotPlatform/dataset/assets/pick_and_place_black_package_obs_ee_action_dee
  episode: 3                                        # 想回放的轨迹编号，从 0 开始

action:
  type: command_end_effector_pose_delta            # 视你的数据而定
  orientation: euler                         

observation:
  type: end_effector_pose
  orientation: quaternion

gripper:
  max_position: 0.08

enable_hardware: false                              # 先测仿真可设 false
reset_robot: true
strict_fps: true                                   # 严格按数据集 FPS 等待
# python -m learning_factory.scripts.lerobot_replay --config learning_factory/configs/robot_motion_replay.yaml