robot_motion_config: factory/tasks/config/robot_motion_fr3_cfg.yaml

dataset:
  repo_id: fr3_pick_and_place_3dmouse
  root: /home/hanyu/code/HIROLRobotPlatform/dataset/assets/fr3_pick_and_place_3dmouse_ee_sop
  action_type: joint_position
  action_ori_type: euler

policy:
  path: outputs/train/fr3_pi0_local/checkpoints/last/pretrained_model

device: cuda
enable_hardware: true
task: "Pick and place with pi0 policy"
observation_type: end_effector_pose
observation_orientation: quaternion
action_type: joint_position
action_ori_type: euler
episode_timeout_s: 30
max_episodes: null

gripper:
  max_position: 1
